// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zidfuvbzancmhirlrhtc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppZGZ1dmJ6YW5jbWhpcmxyaHRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MjIwNDgsImV4cCI6MjA2MDk5ODA0OH0.o92X84F1_lxdOOZ2p5uubAbLN7Gsxy4HqgRbuIc70D0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);